name: Generate Snake

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user: Khushi-4
          svg: true

      - name: Upload Snake animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: ./snake.svg

